Add custom control option for RuleGroup component
react-querybuilder/react-querybuilder pull request #141
Opened 2020-06-11 13:32 UTC by rbalaine

This pull request allow to customize the RuleGroup component. As Rule component is a part of it, it's now accessible when using this module. Furthermore, I fixed an issue with copy-webpack-plugin (caused by the recent package upgrade).

2020-06-11 15:54 UTC, jakeboone02 commented
Thanks, @rbalaine!  Does this resolve #133?

2020-06-11 18:43 UTC, jakeboone02 requested changes
@rbalaine - please see review comments

2020-06-11 18:43 UTC, jakeboone02 commented on index.d.ts
> +
These are incorrect.  They should match the props for `<RuleGroup />`.  Something like this:

```ts
interface RuleGroupCustomControlProps {
  id?: string;
  parentId?: string;
  combinator?: string;
  rules?: [];
  translations?: {};
  schema?: {};
  not?: boolean;
}
```
We may need to specify the `schema` attributes.  For `translations`, we can reuse the definition from below under `interface QueryBuilderProps {...}`.

2020-06-11 18:43 UTC, jakeboone02 commented on src/index.js
> +export { Rule };
Here you can do this in one line:
```js
export { Rule } from './Rule';
```

2020-06-12 08:43 UTC, rbalaine commented
@jakeboone02 Thanks for your comments, I'm fixing that. It doesn't fix #133, only RuleGroup is now customizable. But I saw that artenator did it on his fork, he could make a Pull Request for it.

2020-06-12 15:25 UTC, jakeboone02 approved these changes

2020-06-12 15:26 UTC, merged