Add translations property to be able to set translatable texts.
react-querybuilder/react-querybuilder pull request #47
Opened 2017-11-28 22:51 UTC by bubenkoff

Closes #45

2017-11-29 03:20 UTC, pavanpodila requested changes

2017-11-29 03:20 UTC, pavanpodila commented on README.md
> +This can be used to override translatable texts applie to various controls
typo here: "applied"

2017-12-01 03:55 UTC, bubenkoff commented on README.md
> +This can be used to override translatable texts applie to various controls
done

2017-12-04 01:03 UTC, bubenkoff commented
@pavanpodila please re-review

2017-12-04 03:14 UTC, merged

2017-12-07 18:21 UTC, bubenkoff commented
@pavanpodila  thanks!
can you please make a new release?

2017-12-11 16:21 UTC, pavanpodila commented
@bubenkoff Just published: https://www.npmjs.com/package/react-querybuilder

Thanks for helping out :-)

2017-12-11 16:22 UTC, pavanpodila commented
Tweeted: https://twitter.com/pavanpodila/status/940255179311648768

Feel free to retweet :-)