take initial value prop
react-querybuilder/react-querybuilder pull request #58
Opened 2018-03-19 13:59 UTC by Jebpro

2018-03-19 14:30 UTC, pavanpodila requested changes
Also need a unit test to prove this works ;-). Good job so far!

2018-03-19 14:30 UTC, pavanpodila commented on src/QueryBuilder.jsx
> +        const {fields, initValue, operators, combinators, controlElements, controlClassnames} = this.props;
You are thinking right! I suggest we use the `this.props.query` itself to take in the initial value. There would be no need for a new prop.

2018-03-19 14:30 UTC, pavanpodila commented on src/QueryBuilder.jsx
> +        return this.props.query || this.createRuleGroup(initValue);
Here you can pass in `this.props.query` to `this.createRuleGroup()`.

2018-03-21 07:58 UTC, Jebpro commented
It seems that the query prop was exactly the missing piece I was looking for all along. It should be documented but when I tried to use the query prop on the component and I gave the query json to it, everything worked great. It populated the query builder with groups and rules just as I wanted. Therefore no PR for this feature is necessary as it does work but is just missing documentation.

2018-03-21 08:02 UTC, pavanpodila commented
Can you make a PR to add that to readme? 😇
Many folks have asked for it!

Regards,

--
Pavan Podila

On 21 Mar 2018, 1:28 PM +0530, Jesse Makslahti <notifications@github.com>, wrote:
> It seems that the query prop was exactly the missing piece I was looking for all along. It should be documented but when I tried to use the query prop on the component and I gave the query json to it, everything worked great. It populated the query builder with groups and rules just as I wanted. Therefore no PR for this feature is necessary as it does work but is just missing documentation.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-03-21 08:04 UTC, closed without merging